
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# light:
#   - platform: mqtt
#     schema: json
#     name: "Light 1"
#     state_topic: "herbiOs/lights/light1"
#     command_topic: "herbiOs/lights/light1"
#     brightness: true
#     color_mode: true
#     supported_color_modes: ["brightness"]
