version: '3'
services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host
    ports:
      - "8123:8123"
  
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-logs:/mosquitto/log
    # network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"

  # 1883:1883 -p 9001:9001 